name: royalrumble
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  audioplayers: ^5.2.1
  shared_preferences: ^2.3.5
  sensors_plus: ^6.1.1
  flame: ^1.18.0
  get: ^4.6.6
  nearby_connections: ^4.3.0
  permission_handler: ^11.3.0
  location: ^6.0.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sounds/
    - assets/quiz/images/

flutter_native_splash:
  color: "#001a33"
  image: assets/logo.png
  android_12:
    color: "#001a33"
    image: assets/logo.png
  fullscreen: true
